export const CHANGE_BANNER_LIST = 'recommend/CHANGE_BANNER_LIST';
export const CHANGE_RECOMMEND_LIST = 'recommend/CHANGE_RECOMMEND_LIST';
export const CHANGE_ENTER_LOADING = 'recommend/CHANGE_ENTER_LOADING';